sonar.organization=pravinmoreone-ux
sonar.projectKey=pravin-devops-platform
sonar.projectName=Pravin DevOps Platform
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.sourceEncoding=UTF-8
