sonar.organization=pravinmoreone-ux
sonar.projectKey=pravin-devops-platform
sonar.projectName=Pravin DevOps Platform

sonar.sources=apps/springboot/src/main/java
sonar.java.binaries=apps/springboot/target/classes

sonar.sourceEncoding=UTF-8
