apiVersion: v2
name: opentelemetry-collector
description: OpenTelemetry Collector for metrics, logs, and traces
type: application
version: 0.1.0
appVersion: "0.106.0"
dependencies:
  - name: opentelemetry-collector
    version: "0.106.0"
    repository: "https://open-telemetry.github.io/opentelemetry-helm-charts"