---
- name: Check AWS CLI installation
  ansible.builtin.command: aws --version
  register: aws_cli_check
  changed_when: false
  failed_when: false

- name: Download AWS CLI
  ansible.builtin.get_url:
    url: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
    dest: /tmp/awscliv2.zip
    mode: "0644"
  when: aws_cli_check.rc != 0

- name: Extract AWS CLI archive
  ansible.builtin.unarchive:
    src: /tmp/awscliv2.zip
    dest: /tmp
    remote_src: true
  when: aws_cli_check.rc != 0

- name: Install AWS CLI
  ansible.builtin.command: /tmp/aws/install
  when: aws_cli_check.rc != 0
