---
- name: Check Helm installation
  ansible.builtin.command: helm version
  register: helm_check
  changed_when: false
  failed_when: false

- name: Download Helm installer
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3"
    dest: /tmp/get_helm.sh
    mode: "0755"
  when: helm_check.rc != 0

- name: Install Helm
  ansible.builtin.command: /tmp/get_helm.sh
  when: helm_check.rc != 0
