replicaCount: 2

image:
  repository: ghcr.io/pravinmoreone-ux/pravin-devops-platform/springboot
  tag: "sha-0518d7bc8df05c11421691425c1cf9eee1ee0dee"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

containerPort: 8080
