replicaCount: 2

image:
  repository: ghcr.io/pravinmoreone-ux/pravin-devops-platform/springboot
  tag: "sha-9bb2f6e5117a5197fdb6b233e0634e6ddbaec444"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

containerPort: 8080
