replicaCount: 2

image:
  repository: ghcr.io/pravinmoreone-ux/pravin-devops-platform/springboot
  tag: "sha-90efff0fc524c7131c03a27dfb4c2aef3755ef59"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

containerPort: 8080
