name: Ansible CI

on:
  pull_request:
    paths:
      - "ansible/**"
      - ".github/workflows/ansible-ci.yml"
  push:
    branches:
      - main
    paths:
      - "ansible/**"
      - ".github/workflows/ansible-ci.yml"

jobs:
  ansible:
    name: Ansible Validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Ansible
        run: pip install ansible

      - name: Install Ansible collections
        run: ansible-galaxy collection install -r ansible/requirements.yml

      - name: Check Ansible syntax
        working-directory: ansible
        run: ansible-playbook --syntax-check playbooks/site.yml
