name: Terraform CI

on:
  pull_request:
    paths:
      - "terraform/**"
      - "policy/terraform/**"
      - ".github/workflows/terraform-ci.yml"

  push:
    branches:
      - main
    paths:
      - "terraform/**"
      - "policy/terraform/**"
      - ".github/workflows/terraform-ci.yml"

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: Terraform Validation
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Validate
        run: terraform validate

      - name: Show GitHub OIDC context
        run: |
          echo "Event: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          echo "Repository: ${{ github.repository }}"
          echo "Workflow: ${{ github.workflow }}"        

      - name: Configure AWS credentials
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::263824391433:role/pravin-devops-platform-github-actions
          aws-region: ap-south-1

      - name: Terraform Plan
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform plan -out=tfplan

      - name: Convert Terraform Plan to JSON
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform show -json tfplan > tfplan.json

      - name: Install OPA
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: open-policy-agent/setup-opa@v2
        with:
          version: latest

      - name: OPA Terraform Policy Check
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          result=$(opa eval \
            --format=json \
            -d ../policy/terraform/instance_types.rego \
            -i tfplan.json \
            "data.terraform.instance_types.deny")

          echo "$result"

          deny_count=$(echo "$result" | jq '[.result[0].expressions[0].value[]] | length')

          if [ "$deny_count" -gt 0 ]; then
            echo "OPA policy violations detected."
            exit 1
          fi

          echo "OPA policy check passed."

      - name: Install Trivy
        uses: aquasecurity/setup-trivy@e07451d2e059ed86c2870430ea286b3a9e0bf241
        with:
          version: v0.74.0

      - name: Trivy Terraform Security Scan
        run: trivy config . --severity HIGH,CRITICAL --exit-code 1 --ignorefile ../.trivyignore